language: android
dist: trusty
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master
    - dev

jobs:
  include:
    - install: ./gradlew assemble -PnoJavadoc=true -Prelease=$TRAVIS_PULL_REQUEST
      script: ./gradlew check -Prelease=$TRAVIS_PULL_REQUEST
      os: linux
      jdk: openjdk8
    - install: ./gradlew assemble -PnoJavadoc=true -Prelease=$TRAVIS_PULL_REQUEST
      script: ./gradlew check -Prelease=$TRAVIS_PULL_REQUEST
      os: linux
      jdk: oraclejdk8

    - stage: release
      os: linux
      jdk: openjdk8
      before_script:
        - git config --local user.name "Travis CI Deployment Bot"
        - git config --local user.email "deploy@travis-ci.org"
        - ./gradlew tag -Prelease
      script: ./gradlew assemble deploy -Penv=prod -Prelease
      after_success:
        - bash <(curl -s https://codecov.io/bash)


stages:
  - test
  - name: release
    if: branch = master AND tag IS blank AND type IN (push)

